version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: company-directory-server
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ".:/application"
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      LOG_LEVEL: 'debug'
      APP_ENV: 'dev'
      DATABASE_URL: "postgresql://postgres:testingpass@postgres:5432/app?serverVersion=13&charset=utf8"

  postgres:
    image: postgres
    container_name: company-directory-postgres
    ports:
      - "5433:5432"
    environment:
      # You should definitely change the password in production
      POSTGRES_PASSWORD: 'testingpass'
    volumes:
      - company-directory-db-data:/var/lib/postgresql/data:rw

volumes:
  company-directory-db-data: